// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8rKtn_4EP2R0AKlSTDn3hcBstiyQPUnI',
    appId: '1:61643766623:web:928d257a2b780bbe6394ea',
    messagingSenderId: '61643766623',
    projectId: 'auth-26209',
    authDomain: 'auth-26209.firebaseapp.com',
    storageBucket: 'auth-26209.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGoC8OXRkxhVUCvpT4ov9wFs3QCZTC0IE',
    appId: '1:61643766623:android:a7ab0c3d08a6633e6394ea',
    messagingSenderId: '61643766623',
    projectId: 'auth-26209',
    storageBucket: 'auth-26209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmBncp2zvvlhEaK-JlL_m1j_nzoqKQdU4',
    appId: '1:61643766623:ios:b50b2beb3c0111e86394ea',
    messagingSenderId: '61643766623',
    projectId: 'auth-26209',
    storageBucket: 'auth-26209.appspot.com',
    iosClientId: '61643766623-eki857p9v18onsmlapuiji5qu7dp2nvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmBncp2zvvlhEaK-JlL_m1j_nzoqKQdU4',
    appId: '1:61643766623:ios:0b6163ac499952ac6394ea',
    messagingSenderId: '61643766623',
    projectId: 'auth-26209',
    storageBucket: 'auth-26209.appspot.com',
    iosClientId: '61643766623-fh53vit9lgrcgjnorvhh8n45d3fm750t.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
